---
name: Add version to salt-minion.sls on salt-winrepo-ng

on:
  release:
  workflow_dispatch:
    inputs:
      saltVersion:
        description: 'Salt Version'
        required: true
      winrepoRepo:
        description: 'winrepo repository'
        default: twangboy/salt-winrepo-ng
#        default: saltstack/salt-winrepo-ng

permissions:
  contents: read

jobs:
  update-winrepo:
    name: Update WinRepo
    runs-on: ubuntu-latest
    steps:

    - name: Checkout WinRepo
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.winrepoRepo }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Add Version to Minion Definition File
      run: |
        python .github/workflows/scripts/update_winrepo.py \
          --file <path to salt-minion.py> \
          --version ${{ github.event.inputs.saltVersion }}

    - name: Check for changes
      run: git status

    - name: Stage changes
      run: git add .

    - name: Commit changes
      run: git commit -m 'Adding salt minion ${{ github.event.inputs.saltVersion }}'

    - name: Create Pull Request
      id: cpr
      uses: pter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}

#    - name: Enable Pull Request Automerge
#      if: steps.cpr.outputs.pull-request-operation == 'created'
#      uses: peter-evans/enable-pull-request-automerge@v2
#      with:
#        token: ${{ secrets.PAT }}
#        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
#        merge-method: squash
